In [1]:
import autosklearn.classification
import pandas as pd
from joblib import dump, load
import numpy as np
import glob

/opt/conda/lib/python3.7/site-packages/pyparsing.py:3174: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)


In [2]:
models = []
for model_path in glob.glob("model_3cv/model_run_*"):
    models.append(load(model_path))

In [3]:
bad_models = []
for model_path in glob.glob("model_3cv/bad_auto_model_run_*"):
    bad_models.append(load(model_path))

In [4]:
numeric_conv_cols = ['age', 'age_o', 'importance_same_race', 'importance_same_religion', 'pref_o_attractive', 'pref_o_sincere',\
                    'pref_o_intelligence', 'pref_o_funny', 'pref_o_ambitious', 'pref_o_shared_interests', 'attractive_o', 'sinsere_o', \
                    'intelligence_o', 'funny_o', 'ambitous_o', 'shared_interests_o', 'attractive_important', 'sincere_important', \
                    'intellicence_important', 'funny_important', 'ambtition_important', 'shared_interests_important', \
                    'attractive', 'sincere', 'intelligence', 'funny', 'ambition', 'attractive_partner', 'sincere_partner', \
                     'intelligence_partner', 'funny_partner', 'ambition_partner', 'shared_interests_partner', 'sports', \
                     'tvsports', 'exercise', 'dining', 'museums', 'art', 'hiking', 'gaming', 'clubbing', 'reading', 'tv', \
                     'theater', 'movies', 'concerts', 'music', 'shopping', 'yoga', 'interests_correlate', 'expected_happy_with_sd_people', \
                    'expected_num_interested_in_me', 'expected_num_matches', 'like', 'guess_prob_liked', 'met', 'gender']

In [5]:
df = pd.read_csv("speeddating_reduced.csv")
X= df[numeric_conv_cols]
y= df['match']

In [6]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import balanced_accuracy_score, accuracy_score, f1_score, classification_report

In [7]:
y_preds = []
for model in models+bad_models:
    y_preds.append(model.predict(X))

In [8]:
for y_pred in y_preds:
    print(confusion_matrix(y, y_pred))

[[6006  992]
 [ 315 1065]]
[[6176  822]
 [ 317 1063]]
[[5778 1220]
 [ 304 1076]]
[[6824  174]
 [ 754  626]]
[[6877  121]
 [ 793  587]]
[[6903   95]
 [ 843  537]]


In [9]:
for y_pred in y_preds:
    print('BAL_ACC:', balanced_accuracy_score(y, y_pred),
          'ACC:', accuracy_score(y, y_pred),
          'F1:', f1_score(y, y_pred))

BAL_ACC: 0.8149921716763796 ACC: 0.8439961804726666 F1: 0.6197265056735525
BAL_ACC: 0.8264138615173693 ACC: 0.864048698973502 F1: 0.6511485451761102
BAL_ACC: 0.8026873102459916 ACC: 0.8180950107424206 F1: 0.5854189336235038
BAL_ACC: 0.7143794707390517 ACC: 0.8892337073287181 F1: 0.5743119266055047
BAL_ACC: 0.7040358321839366 ACC: 0.890904750537121 F1: 0.5622605363984674
BAL_ACC: 0.6877775637759856 ACC: 0.8880401050370017 F1: 0.5337972166998011


In [10]:
for y_pred in y_preds:
    print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.86      0.90      6998
           1       0.52      0.77      0.62      1380

    accuracy                           0.84      8378
   macro avg       0.73      0.81      0.76      8378
weighted avg       0.88      0.84      0.86      8378

              precision    recall  f1-score   support

           0       0.95      0.88      0.92      6998
           1       0.56      0.77      0.65      1380

    accuracy                           0.86      8378
   macro avg       0.76      0.83      0.78      8378
weighted avg       0.89      0.86      0.87      8378

              precision    recall  f1-score   support

           0       0.95      0.83      0.88      6998
           1       0.47      0.78      0.59      1380

    accuracy                           0.82      8378
   macro avg       0.71      0.80      0.73      8378
weighted avg       0.87      0.82      0.83      8378

              preci

In [11]:
# dummy clf (always 0)
print(classification_report(y, np.zeros(len(y))))

              precision    recall  f1-score   support

           0       0.84      1.00      0.91      6998
           1       0.00      0.00      0.00      1380

    accuracy                           0.84      8378
   macro avg       0.42      0.50      0.46      8378
weighted avg       0.70      0.84      0.76      8378



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
